defaults:
  - checkpoint: last_k
  - data: default
  - debug: no_debug
  - decode: default
  - logger: default
  - logging: default
  - model: default
  - optimizer: default
  - trainer: train
  - _self_
  - override model/backbone: resnet_transformer_baseplus

hydra:
  output_subdir: null
  run:
    dir: ${checkpoint.dirpath}/${experiment_name}

project_name: semi_supervised_usr
experiment_name: usr_ft_lrs2_og_usr_8gb_test
num_workers: 16
hub_disable_progress_bars: true
log_wandb: True
replace_sampler_ddp: False
compile_model: False
fix_seed: True
matmul_precision: high
ckpt_path:
gpus:
test: False
test_avg: False
txt_file:
slurm_job_id:

# OG USR finetuning (no AU, no LoRA)
model:
  pretrained_model_path: /home/hoangbng/AVATAR/AVATAR/models/usr/checkpoints/baseplus_high_resource_lrs3vox2.pth
  pretrained_lm_path:
  transfer_only_encoder: False
  lora:
    enabled: False
  backbone:
    use_au: False

data:
  frames_per_gpu: 1100
  frames_per_gpu_labelled: 1000
  frames_per_gpu_val: 1000
  dataset:
    train_csv: /home/hoangbng/AVATAR/AVATAR/data/train_manifest.csv
    train_labelled_csv: /home/hoangbng/AVATAR/AVATAR/data/train_manifest.csv
    val_csv: /home/hoangbng/AVATAR/AVATAR/data/val_manifest.csv
    test_csv: /home/hoangbng/AVATAR/AVATAR/data/val_manifest.csv
  hub:
    lrs2_repo_prefix: HBaoAL/LRS2
    prefetch_manifest: false
    prefetch_max_workers: 2
  au:
    enabled: False

decode:
  lm_weight: 0.0

trainer:
  strategy: auto
  devices: 1
  num_nodes: 1
  max_epochs: 10
  log_every_n_steps: 1
  precision: bf16-mixed
  accumulate_grad_batches: 1

checkpoint:
  dirpath: /home/hoangbng/usr_ckpts
